### ISSUE TITLE
Override .train and .eval for embedders

### ISSUE THREAD

**Issue by themurtazanazir** [themurtazanazir/vec2text#3]
in `vec2text/models/model_utils.py` the embedders can be overriden to move to `train` mode. That should not be allowed.

**Comment by themurtazanazir** [comment]
@darshanrao please take this up

**Comment by mattf1n** [comment]
The plan for this is to create a class like https://github.com/themurtazanazir/vec2text/blob/70b9509966e0e5b31c2138904462b35457b9bf6b/vec2text/embedders/embeddings.py#L11 except return logprobs instead of embeddings, right?

**Comment by themurtazanazir** [comment]
yes. you dont even need to reimplemet `forward`. that would already be returning logprobs. just a `train` method to override any `mode` coming in.

**Comment by themurtazanazir** [comment]
this is completed for relevant embedders
